# Generated by Django 3.1.2 on 2020-11-08 05:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20201106_1600'),
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='order_address',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='order_name',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='order_phone',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='customer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='accounts.customer'),
            preserve_default=False,
        ),
    ]
