# Generated by Django 3.1.2 on 2020-11-07 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_orderitem_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='order_address',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='order_name',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='order_phone',
        ),
    ]
