# Generated by Django 3.1.2 on 2020-10-30 03:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20201021_2014'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordered_on', models.DateTimeField(auto_now_add=True)),
                ('order_name', models.CharField(max_length=255)),
                ('order_address', models.CharField(max_length=255)),
                ('order_email', models.CharField(blank=True, max_length=255, null=True)),
                ('order_phone', models.CharField(max_length=14)),
                ('order_quantity', models.IntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='store.product')),
            ],
        ),
    ]
