# Generated by Django 3.1.2 on 2020-10-30 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='order_status',
            field=models.CharField(choices=[('PR', 'Processing'), ('SH', 'Shipping'), ('DE', 'Delivered')], default='PR', max_length=3),
        ),
    ]
